### ISSUE TITLE
Classic SOD - Please add BFD 

### ISSUE THREAD

**Issue by Jorvanus** [Talryn/AutoCombatLogger#7]
Currently doesn't auto start in BFD in Classic Season of Discovery

**Comment by infinity8942** [comment]
or does anybody know how to get the BFD ZoneID？

**Comment by Jorvanus** [comment]
> or does anybody know how to get the BFD ZoneID？

Presumably 198?

![image](https://github.com/Talryn/AutoCombatLogger/assets/89010934/865f7e19-6f27-43f9-a860-810f93aa95e4)

**Comment by Talryn** [comment]
I'm guessing it is 48 since it was the zone ID for the BFD dungeon.

I added a new option for the BFD raid under Raid options and pushed a new build.  I'm unable to test it.  Please let me know if it works properly.

**Comment by beachcoffee** [comment]
> I'm guessing it is 48 since it was the zone ID for the BFD dungeon.
> 
> I added a new option for the BFD raid under Raid options and pushed a new build. I'm unable to test it. Please let me know if it works properly.

It doesn't appear to work. If you have it enabled, and the group wipes and zones back in, the logger is turned off.

Edit: It seems that the BFD Raid is seen as a `party` not a `raid` by the API.

https://github.com/Talryn/AutoCombatLogger/blob/ac3690960b55b7bb2d1b70744ef1648e0e41f45e/AutoCombatLogger.lua#L822
returns `type` as `party`

e.g. adding this
```
elseif (type == "party" and areaId == 48 and profile.logRaid == "Yes") then
	print("This is the SOD BFD Raid")
	self:EnableCombatLogging("Raid")
```

near the below line seems to fix it but is not the 'correct' fix.

https://github.com/Talryn/AutoCombatLogger/blob/ac3690960b55b7bb2d1b70744ef1648e0e41f45e/AutoCombatLogger.lua#L853

**Comment by Talryn** [comment]
@beachcoffee Thanks, that is weird and complicates the fix.

Could someone please provide me the output of `/dump GetInstanceInfo()`?  I'm curious to figure out what exactly they changed.  I would have thought it would be flagged as a raid.

I can change the type for Blackfathom Deeps back to a regular instance and it would fix it.  You would just need to find it under dungeons/instances instead of raids.

**Comment by Talryn** [comment]
Since classifying it as a raid doesn't work, I'm going to release a new version where BFD has a 10 player option as an instance.  Please let me know if it works.  I assume it will unless this new BFD has a different or new difficulty level.

To enable/disable logging for this BFD, look under Instances and not Raids.

**Comment by Jorvanus** [comment]
> @beachcoffee Thanks, that is weird and complicates the fix.
> 
> Could someone please provide me the output of `/dump GetInstanceInfo()`? I'm curious to figure out what exactly they changed. I would have thought it would be flagged as a raid.
> 
> I can change the type for Blackfathom Deeps back to a regular instance and it would fix it. You would just need to find it under dungeons/instances instead of raids.

![image](https://github.com/Talryn/AutoCombatLogger/assets/89010934/4e320317-a5da-4253-833f-a3484718d6ea)

**Comment by Jorvanus** [comment]
![image](https://github.com/Talryn/AutoCombatLogger/assets/89010934/6deef7ad-0842-4596-a66d-8c5af908822b)

![image](https://github.com/Talryn/AutoCombatLogger/assets/89010934/0ba391e6-ab0a-4042-a185-82181ef88b42)

![image](https://github.com/Talryn/AutoCombatLogger/assets/89010934/43fda112-198c-4d1e-9e1a-55b08ccbbf6f)

![image](https://github.com/Talryn/AutoCombatLogger/assets/89010934/aba6e4e0-f6da-42ce-bf66-aa994224b69e)

**Comment by Talryn** [comment]
@Jorvanus Thanks.  The GetInstanceInfo() data helps.  It appears they created a new instance type too.  I pushed 10.1.5 which I hope will work for BFD and will resolve the Lua error.

Thanks for the help and patience.  Let me know if this new version works.

**Comment by JLaferri** [comment]
Is it just me or does this still not work?

**Comment by JLaferri** [comment]
As far as I can tell this is still not working. I put up a PR which fixes it but I haven't spent a ton of time learning how this addon works so this may not be the best way to accomplish the task. Would appreciate some eyes on it.
https://github.com/Talryn/AutoCombatLogger/pull/10

**Comment by Talryn** [comment]
BFD in SoD is actually an instance.  You can actually walk into the new BFD without being in a party or raid group.  It is like UBRS and not a true raid.

You can find the option for it under Instances and there is now an option for the 10 player version.  That option does properly enable/disable logging in BFD.

It may not be intuitive since it is called a raid but it appears the game doesn't treat it like a true raid.  I think it is easier to keep using the data as returned from the game client, otherwise I would need to add a way to map what the game client returns into what Blizzard labels it.  It will be interesting to see how they handle Gnomeregan.

**Comment by JLaferri** [comment]
> BFD in SoD is actually an instance. You can actually walk into the new BFD without being in a party or raid group. It is like UBRS and not a true raid.
> 
> You can find the option for it under Instances and there is now an option for the 10 player version. That option does properly enable/disable logging in BFD.
> 
> It may not be intuitive since it is called a raid but it appears the game doesn't treat it like a true raid. I think it is easier to keep using the data as returned from the game client, otherwise I would need to add a way to map what the game client returns into what Blizzard labels it. It will be interesting to see how they handle Gnomeregan.

I'm sorry where is the option? All I see are the following.
![image](https://github.com/Talryn/AutoCombatLogger/assets/1534726/c2ac1d9b-fd7d-4c16-8605-4f575ac456b6)

**Comment by Talryn** [comment]
If you click that button with the dash or minus symbol to the left of the "Auto Combat Logger" title (in the left window pane), you should see sub-options for Raids, Instances, etc.
